# Generated by Django 3.0.3 on 2020-02-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200222_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Choice_1',
        ),
    ]
