# Generated by Django 3.0.3 on 2020-02-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200225_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice_1',
            new_name='Choice',
        ),
    ]
